/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import java.awt.Color;
import java.math.BigDecimal;
import simulaciones.tp6.Controller;
import java.text.SimpleDateFormat;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabrielneil
 */
public class Tabla extends javax.swing.JFrame {
    Controller controller;
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

    public Tabla(Controller controller) {
        initComponents();
        this.controller = controller;
        _tblSimulacion.setDefaultRenderer(Object.class, new TableCellRenderColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulationTable = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        _scpTabla = new javax.swing.JScrollPane();
        _tblSimulacion = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        verClientes_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultado_txt = new javax.swing.JTextField();
        euler_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vector Estado");

        _tblSimulacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento(0)", "Reloj(1)", "Llegada Cl RND1(2)", "Llegada Cl RND2(3)", "Llegada entre clientes(4)", "Próxima llegada cliente(5)", "Accion RND(6)", "Acción(7)", "Tiempo Fin atención en caja(8)", "RND tiempo espera(9)", "Tiempo espera pedido(10)", "Tiempo entrega pedido(11)", "RND acc mesa(12)", "Acción - Mesa(13)", "RND tiempo uso mesa(14)", "Tiempo de uso de mesa(15)", "Tiempo Fin uso mesa (16)", "RND Tamaño consumicion(17)", "Tamaño consumicion(18)", "Tiempo de consumición(19)", "Tiempo fin de consumición(20)", "Estado Cajero(21)", "Cola Cajero(22)", "Estado Empl 1(23)", "Estado Empl 2(24)", "Cola Empleados(25)", "Tiempo permanencia AC(26)", "Cantidad clientes en cafetería CONT(27)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        _tblSimulacion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        _tblSimulacion.getTableHeader().setReorderingAllowed(false);
        _scpTabla.setViewportView(_tblSimulacion);
        if (_tblSimulacion.getColumnModel().getColumnCount() > 0) {
            _tblSimulacion.getColumnModel().getColumn(0).setPreferredWidth(120);
            _tblSimulacion.getColumnModel().getColumn(1).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(1).setPreferredWidth(70);
            _tblSimulacion.getColumnModel().getColumn(2).setPreferredWidth(50);
            _tblSimulacion.getColumnModel().getColumn(3).setPreferredWidth(50);
            _tblSimulacion.getColumnModel().getColumn(4).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(4).setPreferredWidth(150);
            _tblSimulacion.getColumnModel().getColumn(5).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(5).setPreferredWidth(150);
            _tblSimulacion.getColumnModel().getColumn(6).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(6).setPreferredWidth(50);
            _tblSimulacion.getColumnModel().getColumn(7).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(7).setPreferredWidth(150);
            _tblSimulacion.getColumnModel().getColumn(8).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(8).setPreferredWidth(200);
            _tblSimulacion.getColumnModel().getColumn(9).setPreferredWidth(50);
            _tblSimulacion.getColumnModel().getColumn(10).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(10).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(11).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(11).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(12).setPreferredWidth(50);
            _tblSimulacion.getColumnModel().getColumn(13).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(13).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(14).setPreferredWidth(50);
            _tblSimulacion.getColumnModel().getColumn(15).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(15).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(16).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(16).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(17).setPreferredWidth(50);
            _tblSimulacion.getColumnModel().getColumn(19).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(19).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(20).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(20).setPreferredWidth(170);
            _tblSimulacion.getColumnModel().getColumn(21).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(21).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(22).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(22).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(23).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(23).setPreferredWidth(170);
            _tblSimulacion.getColumnModel().getColumn(24).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(24).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(25).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(25).setPreferredWidth(160);
            _tblSimulacion.getColumnModel().getColumn(26).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(26).setPreferredWidth(200);
            _tblSimulacion.getColumnModel().getColumn(27).setResizable(false);
            _tblSimulacion.getColumnModel().getColumn(27).setPreferredWidth(220);
        }
        _tblSimulacion.getAccessibleContext().setAccessibleName("");
        _tblSimulacion.getAccessibleContext().setAccessibleDescription("");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        verClientes_btn.setText("Ver Clientes");
        verClientes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClientes_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Tiempo promedio de permanencia:");

        resultado_txt.setEditable(false);
        resultado_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado_txtActionPerformed(evt);
            }
        });

        euler_btn.setText("Ver Euler");
        euler_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euler_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(371, 371, 371)
                .addComponent(verClientes_btn)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(euler_btn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(_scpTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 2665, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(_scpTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verClientes_btn)
                            .addComponent(jLabel1)
                            .addComponent(resultado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(euler_btn))
                        .addContainerGap())))
        );

        simulationTable.addTab("Simulacion", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simulationTable))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simulationTable, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verClientes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClientes_btnActionPerformed
       controller.mostrarClientes();
    }//GEN-LAST:event_verClientes_btnActionPerformed

    private void resultado_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado_txtActionPerformed
    }//GEN-LAST:event_resultado_txtActionPerformed

    private void euler_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euler_btnActionPerformed
        // TODO add your handling code here:
        controller.mostrarEuler();
//           _tblSimulacion.setBackground(Color.red);
    }//GEN-LAST:event_euler_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane _scpTabla;
    public javax.swing.JTable _tblSimulacion;
    private javax.swing.JButton euler_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField resultado_txt;
    private javax.swing.JTabbedPane simulationTable;
    private javax.swing.JButton verClientes_btn;
    // End of variables declaration//GEN-END:variables

    public void setResultado(BigDecimal resultado){
        resultado_txt.setText(String.valueOf(resultado));
    }
}
